USE ROLE SYSADMIN;
USE WAREHOUSE WH_XS;
USE DATABASE DEMO_DB;
USE SCHEMA RAW;

-- File format for CSV
CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE = 'CSV'
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Stage for incoming S3 files
CREATE OR REPLACE STAGE STG_S3_INCOMING
  URL = 's3://<your-bucket-name>/'
  STORAGE_INTEGRATION = S3_INT
  FILE_FORMAT = FF_CSV;

-- List files in the stage
LIST @STG_S3_INCOMING;

-- Target table
CREATE OR REPLACE TABLE CUSTOMERS_S3 (
  id INT,
  name STRING,
  city STRING
);

-- Load data
COPY INTO CUSTOMERS_S3
  FROM @STG_S3_INCOMING
  FILES = ('customers.csv')
  ON_ERROR = 'ABORT_STATEME
